float64 roll    # rotation about the x-axis
                # range is about -0.8 to 0.8
float64 pitch   # rotation about the y-axis
                # negative to look up, positive to look down
                # range is about -0.6 to 0.6
float64 yaw     # rotation about the z-axis
                # negative to look left, positive to look right
                # range is about -0.3 to 0.3
---